cmake_minimum_required(VERSION 3.22)

option(BUILD_TEST "Build tests" OFF)
option(BUILD_TEST_FREERTOS "Bild FreeRTOS tests" OFF)
if(NOT BUILD_TEST)
    set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/CMake/toolchain-arm-gcc.cmake)
endif()

project(MotorsController)

if(BUILD_TEST)
    enable_testing()
    if(BUILD_TEST_FREERTOS)
        add_subdirectory(RtosTests)
    else()
        add_subdirectory(Tests)
    endif()
else()
    add_subdirectory(Src)
endif()
